version: '3.1'

services:
    app:
        build: ./tuitionCenterNode
        command: npm start
        volumes: 
            - ./tuitionCenterNode:/app
            - /app/node_modules
        depends_on:
            - db
        ports:
            - "3000:3000"
    db:
        image: mysql:5.7.28
        environment: 
            MYSQL_USER: dhar
            MYSQL_PASSWORD: dhar
            MYSQL_ROOT_PASSWORD: KalaChashma